# Generated by Django 4.0.3 on 2022-03-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolist',
            new_name='todolistt',
        ),
    ]
